# Generated by Django 4.2 on 2023-04-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapedia', '0004_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
