# Generated by Django 4.2 on 2023-04-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapedia', '0005_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_link',
            field=models.URLField(null=True),
        ),
    ]
