# Generated by Django 4.2 on 2023-04-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapedia', '0006_book_preview_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.CharField(null=True),
        ),
    ]
